# Generated by Django 6.0.5 on 2026-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralalert',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behavioralalert',
            name='predicted_threat_level',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='employeebehaviorprofile',
            name='average_login_hour',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employeebehaviorprofile',
            name='common_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeebehaviorprofile',
            name='normal_activity_patterns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
